"""Initial migration

Revision ID: b6f3b7f2a91a
Revises: 
Create Date: 2026-02-22 13:34:33.770756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6f3b7f2a91a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fen', sa.String(length=100), nullable=False),
    sa.Column('moves', sa.JSON(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('themes', sa.JSON(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_puzzle_rating', 'puzzles', ['rating'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tournament_type', sa.Enum('SWISS', 'ROUND_ROBIN', 'KNOCKOUT', name='tournamenttype'), nullable=False),
    sa.Column('time_control', sa.String(length=20), nullable=True),
    sa.Column('base_time', sa.Integer(), nullable=True),
    sa.Column('increment', sa.Integer(), nullable=True),
    sa.Column('rounds', sa.Integer(), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('min_rating', sa.Integer(), nullable=True),
    sa.Column('max_rating', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UPCOMING', 'REGISTRATION', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='tournamentstatus'), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('registration_opens', sa.DateTime(), nullable=True),
    sa.Column('registration_closes', sa.DateTime(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('preferred_board_theme', sa.String(length=50), nullable=True),
    sa.Column('preferred_piece_set', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('friendships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('friend_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'BLOCKED', name='friendshipstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_friendship_user', 'friendships', ['user_id', 'status'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('white_player_id', sa.UUID(), nullable=False),
    sa.Column('black_player_id', sa.UUID(), nullable=False),
    sa.Column('time_control', sa.String(length=20), nullable=True),
    sa.Column('base_time', sa.Integer(), nullable=True),
    sa.Column('increment', sa.Integer(), nullable=True),
    sa.Column('pgn', sa.Text(), nullable=True),
    sa.Column('fen', sa.String(length=100), nullable=True),
    sa.Column('moves', sa.JSON(), nullable=True),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('termination', sa.String(length=50), nullable=True),
    sa.Column('winner_id', sa.UUID(), nullable=True),
    sa.Column('game_type', sa.String(length=20), nullable=True),
    sa.Column('tournament_id', sa.UUID(), nullable=True),
    sa.Column('opening_name', sa.String(length=100), nullable=True),
    sa.Column('opening_eco', sa.String(length=10), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['black_player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['white_player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_game_players', 'games', ['white_player_id', 'black_player_id'], unique=False)
    op.create_index('idx_game_started_at', 'games', ['started_at'], unique=False)
    op.create_index('idx_game_tournament', 'games', ['tournament_id'], unique=False)
    op.create_table('player_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('current_win_streak', sa.Integer(), nullable=True),
    sa.Column('best_win_streak', sa.Integer(), nullable=True),
    sa.Column('current_loss_streak', sa.Integer(), nullable=True),
    sa.Column('daily_streak', sa.Integer(), nullable=True),
    sa.Column('last_played_date', sa.Date(), nullable=True),
    sa.Column('games_today', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('puzzle_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('puzzle_id', sa.UUID(), nullable=False),
    sa.Column('solved', sa.Boolean(), nullable=False),
    sa.Column('time_taken', sa.Integer(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_puzzle_attempt_user', 'puzzle_attempts', ['user_id', 'attempted_at'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('time_control', sa.Enum('BULLET', 'BLITZ', 'RAPID', 'CLASSICAL', name='timecontrol'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('rating_deviation', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'time_control', name='uq_user_time_control')
    )
    op.create_index('idx_rating_time_control', 'ratings', ['time_control', 'rating'], unique=False)
    op.create_table('tournament_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('color_balance', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tournament_participant', 'tournament_participants', ['tournament_id', 'user_id'], unique=False)
    op.create_table('challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenger_id', sa.UUID(), nullable=False),
    sa.Column('challenged_id', sa.UUID(), nullable=False),
    sa.Column('time_control', sa.String(length=20), nullable=True),
    sa.Column('game_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', name='challengestatus'), nullable=True),
    sa.Column('game_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenged_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['challenger_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_challenge_challenged', 'challenges', ['challenged_id', 'status'], unique=False)
    op.create_index('idx_challenge_challenger', 'challenges', ['challenger_id', 'status'], unique=False)
    op.create_table('game_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('white_accuracy', sa.Float(), nullable=True),
    sa.Column('black_accuracy', sa.Float(), nullable=True),
    sa.Column('white_blunders', sa.Integer(), nullable=True),
    sa.Column('white_mistakes', sa.Integer(), nullable=True),
    sa.Column('white_inaccuracies', sa.Integer(), nullable=True),
    sa.Column('black_blunders', sa.Integer(), nullable=True),
    sa.Column('black_mistakes', sa.Integer(), nullable=True),
    sa.Column('black_inaccuracies', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    op.create_table('moves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=5), nullable=False),
    sa.Column('san', sa.String(length=10), nullable=False),
    sa.Column('uci', sa.String(length=10), nullable=False),
    sa.Column('fen_after', sa.String(length=100), nullable=False),
    sa.Column('time_left', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_pairings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('white_player_id', sa.UUID(), nullable=False),
    sa.Column('black_player_id', sa.UUID(), nullable=True),
    sa.Column('game_id', sa.UUID(), nullable=True),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['black_player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['white_player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tournament_round', 'tournament_pairings', ['tournament_id', 'round_number'], unique=False)
    op.create_table('move_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_analysis_id', sa.UUID(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=5), nullable=False),
    sa.Column('san', sa.String(length=10), nullable=False),
    sa.Column('uci', sa.String(length=10), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('eval_before', sa.Float(), nullable=True),
    sa.Column('eval_after', sa.Float(), nullable=True),
    sa.Column('best_move_san', sa.String(length=10), nullable=True),
    sa.Column('best_move_uci', sa.String(length=10), nullable=True),
    sa.Column('is_best_move', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_analysis_id'], ['game_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('move_analyses')
    op.drop_index('idx_tournament_round', table_name='tournament_pairings')
    op.drop_table('tournament_pairings')
    op.drop_table('moves')
    op.drop_table('game_analyses')
    op.drop_index('idx_challenge_challenger', table_name='challenges')
    op.drop_index('idx_challenge_challenged', table_name='challenges')
    op.drop_table('challenges')
    op.drop_index('idx_tournament_participant', table_name='tournament_participants')
    op.drop_table('tournament_participants')
    op.drop_index('idx_rating_time_control', table_name='ratings')
    op.drop_table('ratings')
    op.drop_index('idx_puzzle_attempt_user', table_name='puzzle_attempts')
    op.drop_table('puzzle_attempts')
    op.drop_table('player_stats')
    op.drop_index('idx_game_tournament', table_name='games')
    op.drop_index('idx_game_started_at', table_name='games')
    op.drop_index('idx_game_players', table_name='games')
    op.drop_table('games')
    op.drop_index('idx_friendship_user', table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tournaments')
    op.drop_index('idx_puzzle_rating', table_name='puzzles')
    op.drop_table('puzzles')
    # ### end Alembic commands ###
